- name: check distibution
  fail:
    msg: "Unsupported distro {{ ansible_distribution }}"
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Debian'

- block:
    - name: install dependencies
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present
        update_cache: yes
    - name: add repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  when: ansible_distribution == 'Ubuntu'

- block:
    - name: install dependencies
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg2", "software-properties-common"]
        state: present
        update_cache: yes
    - name: add repository key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: add repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
  when: ansible_distribution == 'Debian'

- name: install docker-ce
  apt:
    name: [ "docker-ce", "docker-ce-cli", "containerd.io" ]
    update_cache: yes
  notify:
    - install_pip
    - install_docker_module

- name: enable and start
  systemd:
    name: docker
    state: started
    enabled: yes
