- fail:
    msg: "Unsupported distro {{ ansible_distribution }}"
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Debian'

- name: install dependencies [Ubuntu]
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
    state: present
    update_cache: yes
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: install dependencies [Debian]
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg2", "software-properties-common"]
    state: present
    update_cache: yes
  become: yes
  when: ansible_distribution == 'Debian'

- name: add repository key [Ubuntu]
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: add repository key [Debian]
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: yes
  when: ansible_distribution == 'Debian'

- name: add repository [Ubuntu]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: add repository [Debian]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
  become: yes
  tags: debug
  when: ansible_distribution == 'Debian'

- name: install docker-ce
  apt:
    name: [ "docker-ce", "docker-ce-cli", "containerd.io" ]
    update_cache: yes
  become: yes

- name: enable and start
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
