global:

route:
  group_by: ['job', 'instance']
  group_wait: 1s
  group_interval: 5m
  repeat_interval: 3h

  receiver: 'telegram'

receivers:
  - name: 'telegram'
    webhook_configs:
    - send_resolved: true
      url: http://localhost:10000
